name: Build/release

on: workflow_dispatch

permissions:
  contents: write

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v6

      - name: Setup Bun ⚙️
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies with Bun
        run: bun install

      - name: Typecheck
        run: bun run typecheck

      - name: Build
        run: bun run postinstall

      - if: matrix.os == 'ubuntu-24.04'
        name: Build Linux
        run: bun run release:linux

      - if: matrix.os == 'ubuntu-24.04'
        name: Build Mac (On Linux)
        run: bun run release:mac

      - if: matrix.os == 'windows-latest'
        name: Build Windows
        run: bun run release:win
